# Generated by Django 4.2 on 2024-12-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realtor',
            new_name='Msglist',
        ),
    ]
